import re

texto = """
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de italia y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
Mejores comidas de ItalXA y qué comer en italia.  italoa. #comerenitalia #comidaitaliana #viajeaitalia
"""

palabra = input('Palabra a buscar: ')
patron = f' {palabra}[. ]'
# it al i a
lista_palabras_italia = re.findall(patron, texto, re.IGNORECASE)
print(f'La palabra {palabra} en el texto sobre comidas de italia se repite {len(lista_palabras_italia)} veces.')
